--- #로컬 설정
spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/heech_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        ues_sql_comment: true
        default_batch_fetch_size: 1000
    open-in-view: true

  messages:
    basename: messages,errors

server:
  port: 10001

logging:
  level:
    root: info
    org.hibernate.SQL: debug